blank_issues_enabled: true
contact_links:
  - name: Chat on Libera
    url: https://web.libera.chat/#omarchy,#omairc
    about: Quick questions and informal chat in #omarchy or #omairc on Libera Chat.
